[package]
name = "pipelines-demo"
version = "0.1.0"
authors = ["danitrod <danitrod@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.0.2"
actix-web = "3.3.2"
actix-files = "0.5.0"
